target-version = "py38"
include = [
    "UnityPy/*.py",
    "UnityPy/*.pyi",
    "tests/*py",
    "setup.py",
    "generators/*.py",
    "examples/*.py",
]
exclude = ["UnityPy/classes/generated.py"]
line-length = 120

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
]

[lint.pydocstyle]
# Enforce numpy-style docstrings
convention = "numpy"

[lint.per-file-ignores]
# Ignore docstring requirements for test files
"tests/**/*.py" = ["D"]
# Ignore undefined names
"UnityPy/streams/EndianBinaryReader.py" = ["F821"]
