target-version = "py37"
include = [
    "UnityPy/*.py",
    "UnityPy/*.pyi",
    "tests/*py",
    "setup.py",
    "generators/*.py",
    "examples/*.py",
]

[lint.pydocstyle]
# Enforce numpy-style docstrings
convention = "numpy"

[lint.per-file-ignores]
# Ignore docstring requirements for test files
"tests/**/*.py" = ["D"]
